### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Grytic** [Dapro718/SimpleAfk#1]
Command /afk <on | off> becomes simple with /afk <message>, example: /afk Im currently afk, Call me later. If message is not filled, there will be an automatic message from config

**Comment by Dapro718** [comment]
So your saying instead of the default ``public-message`` in config, users can set their own custom message?

**Comment by Grytic** [comment]
Yes

**Comment by Dapro718** [comment]
Your suggestions have been added!
